plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // Spring Boot Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Jackson JSON
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.6'

    // Jackson XML
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.18.6'

    // Java Time Support
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.6'

    // GitHub API
    implementation 'org.kohsuke:github-api:1.326'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.register('processAssetPayload', JavaExec) {

    group = 'application'

    classpath = sourceSets.main.runtimeClasspath

    mainClass = 'com.example.webhook.service.HppAssetPayloadProcessor'

    args 'payload.json'
}

tasks.named('test') {
    useJUnitPlatform()
}
