name: Deploy bucket contents

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the target environment to sync'
        required: true
        type: choice
        options:
          - dev
          - sit
          - uat
          - load
          - prod
          - demo

jobs:
  BucketSync:
    name: BucketSync - ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

